name: Run Twitter Bot

on:
  schedule:
    - cron: '0 9 * * *'  # This runs every day at 9:00 AM UTC (adjust as needed)
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run the bot
        run: |
          python bot.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
